services:
  - type: worker
    name: sholooanydlbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/sholoomail/sholooanydlbot.git
    branch: Anydl-bot-for-public
    envVars:
      - key: TG_BOT_TOKEN 
        sync: false
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: CHAT_BASE_TOKEN 
        sync: false
      - key: CHUNK_SIZE 
        value: 128
      - key: AUTH_USERS 
        value: 146676294
      - key: WEBHOOK 
        value: ANYTHING
